### ISSUE TITLE
Can't warp the lower garments.

### ISSUE THREAD

**Issue by arifshahriarnsl** [KiseKloset/DM-VTON#22]
I used the DressCode dataset for training the model. It can warp the upper and full body garments but lower garments can't. What is the problem? Please help.
![43000](https://github.com/KiseKloset/DM-VTON/assets/143155025/0d2667e9-4125-481b-bb27-e12ccc6addaf)

**Comment by zero-nnkn** [comment]
I haven't reviewed your training code, but I guess your issue is the garment mask. In this code, I set the garment mask to upper body garments. So, in the training process, the model will try to fit the lower garments to the upper mask. You can modify your Dresscode Dataset class to get the lower-body garment mask.

![image](https://github.com/KiseKloset/DM-VTON/assets/60695920/91dd2e0f-c343-489e-a948-8beb5d921dde)
